services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aistea\AisteaSeo\:
    resource: '../Classes/*'

  Aistea\AisteaSeo\Middleware\CheckerEndpoint:
    public: true
